NetworkExpansion: 1
ParameterScale: 0
EnergyShareRequirement: 1
TimeDomainReduction: 0
Trans_Loss_Segments: 1
CapacityReserveMargin: 1
StorageLosses: 0
UCommit: 0
MaxCapReq: 0
MinCapReq: 0
CO2Cap: 0
WriteShadowPrices: 1
ComputeConflicts: 1
OperationWrapping: 0
ModelingToGenerateAlternatives: 0
ModelingtoGenerateAlternativeSlack: 0.1
ModelingToGenerateAlternativeIterations: 100
MultiStage: 0
EnableJuMPStringNames: true
